### ISSUE TITLE
Select between bokeh and matplotlib plotting

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross#162]
As we know, the ROSS' functions that plot graphs are plotting both, bokeh and matplotlib graphs. We should: 
- separate in two different methods, like `def plot_bokeh` and `def plot_matplotlib`, or
- insert an argument to select the library, making one of them as default, like `def plot(plot_type="bokeh / matplotlib")`

If we can get bokeh to work properly with sphinx, we should let bokeh as default argument.

 - [x] Rotor
 - [x] Campbell
 - [x] Frequency Response

**Comment by raphaeltimbo** [comment]
I am working on this now.
Regarding the two methods that we can use to accomplish this, I have the following considerations:

> * separate in two different methods, like `def plot_bokeh` and `def plot_matplotlib`, or

In this case, I believe the code is simpler since we don't have to insert if clauses throughout the function. The problem is that we will have two plot functions, which is not so nice.


> * insert an argument to select the library, making one of them as default, like `def plot(plot_type="bokeh / matplotlib")`

It looks natural to have only one plot function, the problem is that we start to have function arguments that are used in one case and are not used on the other case. We also have to specify what is returned by the function. This can make the documentation for the function confusing.

I am still not sure what we should use. For now, I am implementing two separate hidden functions (`._plot_matplotlib()` and `._plot_bokeh()`). These functions are called by a `.plot(plot_type="...")` function.

> If we can get bokeh to work properly with sphinx, we should let bokeh as default argument.
For now, I am keeping matplotlib as default since we have not yet figured out a way to display bokeh plots on the sphinx documentation.
