### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by juvianna** [ross-rotordynamics/ross#238]
There are two repositories in https://github.com/ross-rotordynamics. One called ross and another ross-website, where it is supposed to have a website, right? But I can only find the website at the bottom of the ross repository through a hyperlink "Access the documentation here". Is it correct?

**Comment by flaviorangel** [comment]
The ross-website repository holds the HTML files, but it is not supposed to have a website. It just stores the files in a Git way. It was separated from the main repository because HTML files are usually larger and automatic generated files that mess with develop metrics, such as the number of lines added to the project. For example, the api.html alone has more than 2k lines.

**Comment by raphaeltimbo** [comment]
As @flaviorangel pointed out, the ross-website repository holds the HTML files and the [GitHub Pages](https://pages.github.com/) service builds the website:
![image](https://user-images.githubusercontent.com/18506378/62650275-e0a32a80-b92c-11e9-9c51-55414ac9dd7b.png)
