### ISSUE TITLE
bokeh_patch returning hover tool

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#361]
I saw that the `ShaftElement.bokeh_patch()` method returns a bokeh hover.
Is there a reason for us to return the hover instead of returning bk_ax? 
@rodrigomoliveira1

**Comment by rodrigomoliveira1** [comment]
Actually, yes.

It was necessary to prevent the code from creating a "hover" icon for each shaft element in the model.
Returning a bokeh hover allows me to collect all the information in a single "hover" and then add it to the layout. Otherwise, the `bokeh.figure` would display lots of hover icons on the toolbar.

You'll notice it in `DiskElement.bokeh_patch()` too.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.
