### ISSUE TITLE
Specify programs being used

### ISSUE THREAD

**Issue by flaviorangel** [ross-rotordynamics/ross#53]
This was a suggestion made by @thiagoritto, so that newcomers to the project (or online collaborators) can know straight away which applications they should install and what they do.

**Comment by raphaeltimbo** [comment]
One idea would be to have a section "Dependencies" on README.md.
There we could list the main dependencies and python versions that can be used.
But the user won't have to worry about installing all dependencies since pip will take care of this by looking at the packages listed on the setup.py file (`REQUIRED` variable).

**Comment by flaviorangel** [comment]
What Ritto had in mind when suggesting this issue was more of a way to integrate people to the project than help them run the code. So it would explain applications like pycharm, git, and black more than numpy, matplotlib, etc, specially for people not used to them. But you're right: explaining in the readme that the dependencies are listed on setup.py and how to install them should also be included.

**Comment by raphaeltimbo** [comment]
We could add a section to the documentation related to how to contribute to the project. 
The git configuration (that is already written) could be a subsection of it and we could also add an explanation about black and the other things on that section. 
What do you think?

**Comment by flaviorangel** [comment]
I'll work on it.
