### ISSUE TITLE
Error in the eccentricity ratio for approaching short bearings

### ISSUE THREAD

**Issue by JuliaMota** [ross-rotordynamics/ross#647]
There is a problem with the function that calculates the eccentricity ratio from the Sommerfeld number for approaching short bearings. The function considers a 4th degree polynomial while it should be 8th degree. In addition, there are improvements that can be made in order to obtain a better approximation to the eccentricity in the equilibrium position.

It is worth remembering that the short bearing is widely used and the balance position found by this method is used as an initial kick for the iterative method that seeks the balance position for bearings of any size.

**Comment by alannakamura** [comment]
To find the correct eccentricity rate, the roots of the fourth degree polynomial were taken, complex roots were eliminated, and the real roots were ordered in ascending order. Then I chose the smallest root that had a value between 0 and 1 and returned its square root. The square root was necessary because the polynomial solved in the code was a fourth degree polynomial, so that the square of the eighth degree root was found.
