### ISSUE TITLE
Cylindrical tests taking too long to complete

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross#818]
The tests in the `test_cylindrical.py` file take a long time to complete. 
I will try to decrease this time by changing the number of elements in the calculation and also by grouping some tests.

**Comment by ross-bott** [comment]
Hi there!
I have marked this issue as stale because it has not had activity for 45 days.
Consider the following options:
- If the issue refers to a large task, break it in smaller issues that can be solved in
less than 45 days;
- Label the issue as `wontfix` or `wontfix for now` and close it.

**Comment by marcusfilipesr** [comment]
Hi @raphaeltimbo, I was checking this issue and thought that the tests for `cylindrical` and `cylindrical_units` could be done just once, since it is running twice, but using the `Q_` method in only two different variables. What do you think?

I've also tested with a smaller mesh for the tests, and it is now running in lower time.
